name: Build, push, and deploy

on:
  push:
    branches:
      - feature/naisYaml

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: .*
  build_and_deploy:
    name: Build and push Docker container
    needs: tag
    runs-on: ubuntu-latest
    steps:
      # HENTER NYESTE TAG FOR Ã… BRUKE DET SOM VERSJONSNUMMER
      - uses: actions/checkout@v1
      - name: 'Get Previous tag'
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # OPPRETTER IMAGE VARIABEL MED VERSJONSNUMMER
      - uses: actions/checkout@v1
      - name: 'Set Image'
        run: echo "::set-env name=IMAGE::docker.pkg.github.com/${{ github.repository }}/eessi-pensjon-begrens-innsyn:${{ steps.previoustag.outputs.tag }}"

      # BYGGER DOCKER CONTAINER
      - uses: actions/checkout@v1
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew -Pgithub test build
          docker build --tag ${{ env.IMAGE }} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${{ env.IMAGE }}

      # DEPLOYER TIL NAIS
      - uses: nais/deploy/actions/deploy@v1
      - name: Deploy to NAIS
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais-q2.yml
          VARS: dev-fss-q2.json
          IMAGE: ${{ env.IMAGE }}